// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqOPod6eQxJrhdDk1ZNMQLJi0hsspHt50',
    appId: '1:144980210127:web:f95dbe79090319709b62ba',
    messagingSenderId: '144980210127',
    projectId: 'quizmaker-app',
    authDomain: 'quizmaker-app.firebaseapp.com',
    storageBucket: 'quizmaker-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDt0W4vPmkvJP2C3FobqwyfbSC64xTRO6s',
    appId: '1:144980210127:android:d0a2a5eab0e9a5ce9b62ba',
    messagingSenderId: '144980210127',
    projectId: 'quizmaker-app',
    storageBucket: 'quizmaker-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEbwiU6HC5VpDiAywFIz9PWeLStaJd_f8',
    appId: '1:144980210127:ios:f7e7cf92239528d69b62ba',
    messagingSenderId: '144980210127',
    projectId: 'quizmaker-app',
    storageBucket: 'quizmaker-app.appspot.com',
    iosClientId: '144980210127-03fgchipoj2ktg4b6ohhqm0kepniuk59.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizMaker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEbwiU6HC5VpDiAywFIz9PWeLStaJd_f8',
    appId: '1:144980210127:ios:f7e7cf92239528d69b62ba',
    messagingSenderId: '144980210127',
    projectId: 'quizmaker-app',
    storageBucket: 'quizmaker-app.appspot.com',
    iosClientId: '144980210127-03fgchipoj2ktg4b6ohhqm0kepniuk59.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizMaker',
  );
}
